name: dart_project
description: A Dart project to demonstrate string manipulation, collections, file handling, and date/time utilities.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  